
module.exports = [
	{ capital: 'Montgomery', city: 'Birmingham', stateAbbrev: 'AL' },
	{ capital: 'Juneau', city: 'Anchorage',stateAbbrev: 'AK' },
	{ capital: 'Phoenix', city: 'Tempe',stateAbbrev: 'AZ' },
	{ capital: 'Little Rock', city: 'Fayetteville',stateAbbrev: 'AR' },
	{ capital: 'Sacramento', city: 'Los Angeles',stateAbbrev: 'CA' },
	{ capital: 'Denver', city: 'Boulder',stateAbbrev: 'CO' },
    { capital: 'Hartford', city: 'New Haven',stateAbbrev: 'CT' },
    { capital: 'Washington DC', stateAbbrev: 'DC' },
	{ capital: 'Dover', city: 'Wilmington',stateAbbrev: 'DE' },
	{ capital: 'Tallahassee', city: 'Miami',stateAbbrev: 'FL' },
	{ capital: 'Atlanta', city: 'Savannah',stateAbbrev: 'GA' },
	{ capital: 'Honolulu', city: 'Hilo',stateAbbrev: 'HI' },
	{ capital: 'Boise', city: 'Idaho Falls',stateAbbrev: 'ID' },
	{ capital: 'Springfield', city: 'Chicago',stateAbbrev: 'IL' },
	{ capital: 'Indianapolis', city: 'Gary',stateAbbrev: 'IN' },
	{ capital: 'Des Moines', city: 'Ames',stateAbbrev: 'IA' },
	{ capital: 'Topeka', city: 'Kansas City',stateAbbrev: 'KS' },
	{ capital: 'Frankfort', city: 'Louisville',stateAbbrev: 'KY' },
	{ capital: 'Baton Rouge', city: 'New Orleans',stateAbbrev: 'LA' },
	{ capital: 'Augusta', city: 'Portland',stateAbbrev: 'ME' },
	{ capital: 'Annapolis', city: 'Baltimore',stateAbbrev: 'MD' },
	{ capital: 'Boston', city: 'Cambridge',stateAbbrev: 'MA' },
	{ capital: 'Lansing', city: 'Detroit',stateAbbrev: 'MI' },
	{ capital: 'Saint Paul', city: 'Minneapolis',stateAbbrev: 'MN' },
	{ capital: 'Jackson', city: 'Biloxi',stateAbbrev: 'MS' },
	{ capital: 'Jefferson City', city: 'St. Louis',stateAbbrev: 'MO' },
	{ capital: 'Helena', city: 'Billings',stateAbbrev: 'MT' },
	{ capital: 'Lincoln', city: 'Omaha',stateAbbrev: 'NE' },
	{ capital: 'Carson City', city: 'Las Vegas',stateAbbrev: 'NV' },
	{ capital: 'Concord', city: 'Manchester',stateAbbrev: 'NH' },
	{ capital: 'Trenton', city: 'Hoboken',stateAbbrev: 'NJ' },
	{ capital: 'Santa Fe', city: 'Albuquerque',stateAbbrev: 'NM' },
	{ capital: 'Albany', city: 'New York City',stateAbbrev: 'NY' },
	{ capital: 'Raleigh', city: 'Charlotte',stateAbbrev: 'NC' },
	{ capital: 'Bismarck', city: 'Fargo',stateAbbrev: 'ND' },
	{ capital: 'Columbus', city: 'Cleveland',stateAbbrev: 'OH' },
	{ capital: 'Oklahoma City', city: 'Norman',stateAbbrev: 'OK' },
	{ capital: 'Salem', city: 'Portland',stateAbbrev: 'OR' },
	{ capital: 'Harrisburg', city: 'Philadelphia',stateAbbrev: 'PA' },
	{ capital: 'Providence', city: 'Newport',stateAbbrev: 'RI' },
	{ capital: 'Columbia', city: 'Charleston',stateAbbrev: 'SC' },
	{ capital: 'Pierre', city: 'Sioux Falls',stateAbbrev: 'SD' },
	{ capital: 'Nashville', city: 'Knoxville',stateAbbrev: 'TN' },
	{ capital: 'Austin', city: 'Dallas',stateAbbrev: 'TX' },
	{ capital: 'Salt Lake City', city: 'Provo',stateAbbrev: 'UT' },
	{ capital: 'Montpelier', city: 'Burlington',stateAbbrev: 'VT' },
	{ capital: 'Richmond', city: 'Norfolk',stateAbbrev: 'VA' },
	{ capital: 'Olympia', city: 'Seattle',stateAbbrev: 'WA' },
	{ capital: 'Charleston', city: 'Wheeling',stateAbbrev: 'WV' },
	{ capital: 'Madison', city: 'Milwaukee',stateAbbrev: 'WI' },
	{ capital: 'Cheyenne', city: 'Cody',stateAbbrev: 'WY' }
];